base: 'https://typo13.lvogelmann.ddev.site/'
dependencies:
  - typo3/form
  - schommer-media/smedia-frontend
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: Typo13
