group: contentblocks
name: schommer-media/banner
basics:
  - TYPO3/Appearance
  - TYPO3/Links
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: schommer-media/Colors
    type: Basic
  - identifier: items
    type: Collection
    labelField: link_text
    minitems: 1
    fields:
      - identifier: schommer-media/Image
        type: Basic
      - identifier: schommer-media/Links
        type: Basic

